### ISSUE TITLE
Add a command to toggle pause and play

### ISSUE THREAD

**Issue by J053Fabi0** [siphomateke/deezer#16]
Hello. 

Is it possible to create a command that lets you toggle pause and play? I would like to map some keybindings to that function. 

Something like `deezer --toggle`

**Comment by J053Fabi0** [comment]
If you mean the options available when clicking the tray icon, I know they exist. I don't have system media controllers as far as I'm concerned, I'm using Arch Linux, and I don't have physical buttons for that either. But thank you for the advice, @ToMattBan.

**Comment by siphomateke** [comment]
As @ToMattBan said, you can just use your system's built-in media controls. This Deezer package implements [MPRIS](https://wiki.archlinux.org/title/MPRIS) which allows playback to be controlled using your system's media controller. For example, on KDE, you can assign keyboard shortcuts for that in System Settings > Shortcuts > Play/pause media playback.
