### ISSUE TITLE
Can't install on Linux Mint 21

### ISSUE THREAD

**Issue by edueocara27** [siphomateke/deezer#20]
I am not able to install on Mint 21. I checked and the problem is apparently nodesource, which does not detect this newer version of Mint.

It's possible to apply a workaround to install nodesource on Mint 21. https://github.com/nodesource/distributions/issues/1430#issuecomment-1214345955
The problem is that even if I manage to install nodesource directly, the Deezer installation simply ignores that nodesource has already been installed, installs it again and gives an error because the workaround was not applied and I don't even know if it's possible to apply.

Any solution?

**Comment by siphomateke** [comment]
I don't personally use Mint, so I'm not sure about this specific issue, but if you've already successfully installed Node 14, then you can just remove the nodejs installation from `install.sh`. Specifically, remove

```shell
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
```

and `nodejs` from

```shell
sudo apt install -y p7zip-full imagemagick nodejs wget g++ make patch
```

I could perhaps look into adding a check to see if the correct Node.js version is already installed and skip the install.

**Comment by edueocara27** [comment]
Thanks. Installed and is working perfectly.
