### ISSUE TITLE
A way for setting electron's zoom level/factor

### ISSUE THREAD

**Issue by dcardoso-vibrent** [siphomateke/deezer#6]
It's not really an issue, but I'd like to know if there's a flag in electron, env var or something that could set the zoom to 125% for example, since I'm using a 4K monitor.

Thanks a lot!

**Comment by siphomateke** [comment]
Chromium (which Electron is based on) should already do this as far as I'm aware. I currently use a 125% fractional scaling factor under Kubuntu and Deezer correctly scales to 125% too. Does Deezer's website have the correct scale for you when using Chrome?

If you are unable to get Chrome to use the correct scale, you can also just press Alt to show the menubar in Deezer desktop and manually zoom in or out from the "view" menu.

**Comment by siphomateke** [comment]
Since this is most likely an issue unrelated to Deezer desktop and there is already a suitable workaround, I'm going to close this issue.
