### ISSUE TITLE
Can I put this app in my store?

### ISSUE THREAD

**Issue by ToMattBan** [siphomateke/deezer#7]
Hey man, this isn't a issue, but GitHub don't have any way to send PMs so I'm writing here.

I'm developing a Linux dist and want to put this app in the store. But first I need your permission to do that.

Can I have your permission to put this fabulous port in my store? With the credits, of course.

**Comment by siphomateke** [comment]
Sorry for the extremely late response. I'm fine with you using this in your distribution, as long as you provide credit where it's due. Specifically, to @SibrenVasse (https://github.com/SibrenVasse/deezer) who is the real developer of the Deezer Linux port. This repo is really just a wrapper around their great work.

Also, do keep in mind that you are likely not allowed to redistribute Deezer's binary files so if you include this in any distro, you'll have to make sure that you only download the binary file directly from Deezer.
